### ISSUE TITLE
Source (TF2, GMod, etc) Support

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#14]
Source games seem to start up just fine, but I can't find them in the server lists and the ports don't seem to be open (at least through ADS -- will have to test them standalone).

**Comment by skylaar727** [comment]
Not sure if you got round to testing yourself, but decided to do a bit myself.

Tested initially TF2 and then CS:Source both off of my known working installation of the container using ADS. Like you I found I was unable to find either server in the server list or connect via port.

I tested adding the Game Server Account Token just incase that had any impact. Since in AMP it suggests not having this may lot allow certain games to connect to the internet. No luck after that in on the existing container either, though Valve did register activity on the token so some sort of connection was made there. Again aligns with how judging by console the server itself launches without issue what so ever.

I went ahead and created a duplicate docker container only changing module to srcds. Only tested via CS:Source in this case as it is a much smaller and faster download. I found once again that AMP is perfectly accessible, the server appears to start up fine but again no connectivity to the server itself in game. The token has once again registered this new activity so if it is a port issue, definitely appears to just be the game ports, not any of the web traffic side.

No idea if this is of any help but atleast it gives you a little more data to play with.

**Comment by MitchTalmadge** [comment]
Thank you for doing that! It does help. I'll keep working on this as I get free time, it's limited now that I am back in college.

**Comment by skylaar727** [comment]
So got some time to mess about more this weekend and I've gotten Source games working on my setup.

Was a rather silly oversight actually, not sure if its what was causing issues on your setup. I noticed starbound worked through steam even though source didn't which gave me a bit of a lead. Turns out most the source games use UDP rather than TCP, I only had the ports opened in docker as TCP.

Once opened to UDP no problems what so ever. The port breakdown by Valve can be found here.
https://support.steampowered.com/kb_article.php?ref=8571-GLVN-8711

In the process I also discovered that Minecraft Bedrock Edition also uses UDP while the original Java edition uses TCP. This may therefore also be the resolution for #11 so I'm going to test that out next time I have some spare time, maybe during the week or worst case scenario next weekend.

**Comment by MitchTalmadge** [comment]
Oh of course! That makes a lot of sense and I never would have thought of it. Great work! I'll verify your findings likely tomorrow since it's a holiday :) I seriously appreciate your help in improving this image.

**Comment by skylaar727** [comment]
Not a problem, I honestly came across it by accident because someone wanted to play starbound so I figured I'd test it within this docker image and see if it works or not. Then it just kind of hit me.

Haven't found any other issues while tinkering about so might be looking at a fully working image now. Or I guess it already was and we both just totally blanked on UDP.

**Comment by MitchTalmadge** [comment]
GMod confirmed working after opening port on UDP! 

🚀🚀🚀🚀🚀

![image](https://user-images.githubusercontent.com/8848080/73339347-cbe98480-4235-11ea-97b1-2b9c6be68a9d.png)

Thanks again @skylaar727
