### ISSUE TITLE
Can't login to the user interface

### ISSUE THREAD

**Issue by DrJ4ck** [MitchTalmadge/AMP-dockerized#149]
I am setting up AMP as a docker image but when I access the Web UI, it says invalid username or password. I have tried changing the values or leaving them the same. I have removed the docker image and re-installed it. Any help would be greatly appreciated.

**Comment by Kottonboru** [comment]
If you're still having issues I'm willing to bet its because your password and/or username has Special characters like . or ! in them which does not work and will return a "invalid username and password" error when trying to login.

I would suggest resetting the Login like you already did and do not use special characters. 
Hopefully this helps!

Also, I'm not connected to this Docker but while looking to see if the Issue I was having was on the Issue list I came across yours so hopefully its not a issue that i replied to this.

**Comment by IceOfWraith** [comment]
This is resolved in the latest getamp script so special characters shouldn't be an issue any longer.
