### ISSUE TITLE
Main auto-boot toggles on and off with each reboot.

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#21]
I have noticed that this line in the `entrypoint.sh` file, which is meant to ensure that the `Main` instance is always set to auto-boot, may be _disabling_ auto-boot for Main when it is already set to auto-boot. Like a toggle command, rather than a set command. This was unexpected behavior. Hopefully a fix is not too difficult.

https://github.com/MitchTalmadge/AMP-dockerized/blob/b60b7cc6cff1690b9042e2eff77256b456708cf6/entrypoint.sh#L35

**Comment by MitchTalmadge** [comment]
This line may fix the problem:

```
su amp --command "ampinstmgr ShowInstanceInfo Main | grep \"Start on Boot\" | grep \"No\" && ampinstmgr SetStartBoot Main"
```

**Comment by skylaar727** [comment]
Thanks for this, appears to have fixed an issue I was seeing on my setup that I thought was related to my setup.

I mentioned previously my setup automatically generates SSL certifiactes but I was finding sometimes after container restarts I wouldnt connect and would have to restart again.

Just did my weekly maintenance and updated the image while I was at it, and so far it seems to have resolved the issue. I guess the connection errors were simply because there was no ADS instance running behind it.

Much appreciated.

**Comment by MitchTalmadge** [comment]
Yep very likely this was the problem. I had never really restarted my container except to update AMP and then I noticed this bug. :)
