### ISSUE TITLE
server update not saved when AMP container restarted

### ISSUE THREAD

**Issue by sstretchh** [MitchTalmadge/AMP-dockerized#62]
I set up this container today in unraid and installed a Minecraft server with in AMP and updated the server. when the docker container was restarted, the Minecraft server had to be updated again.

Where does the Minecraft server save when installed in AMP ? I want to make sure its in a file store location vs in the container some where.

**Comment by MitchTalmadge** [comment]
Thanks for the report! Minecraft updates in my experience get downloaded directly into the instance directory alongside the old version jar and the plugins folder and config files and such. They should still be there after a restart as long as you have the `/home/amp/.ampdata` volume mounted (and it sounds like you do). The Minecraft updater has been finicky for me too though in the past, even on a non-docker install. I personally just drag and drop new updated jars into the file manager manually and then change the settings so that the new jar is used. I'll test this though and see if I can reproduce it.
