### ISSUE TITLE
Container not updating on Docker Pull 

### ISSUE THREAD

**Issue by Mattssn** [MitchTalmadge/AMP-dockerized#99]
I have been getting a message on the web ui saying there is an update, normally I would re-pull the image and it would update, but that does not seem to be working now, when I hit update in the UI it just breaks and gives me a 502 error

**Comment by MitchTalmadge** [comment]
Is this UnRAID?

**Comment by Mattssn** [comment]
Sorry for the delayed response, I am using docker compose

**Comment by MitchTalmadge** [comment]
So personally I've never seen an update button for AMP itself in the UI, but I doubt it'd work either way because of how Docker works.

I would just continue to use `docker-compose pull` if possible. I have a script set up in this repo which automatically packages the latest AMP updates and uploads them as Docker images so that you only have to pull and restart the container.
